### ISSUE TITLE
`valid` attribute requires buffering

### ISSUE THREAD

**Issue by tgraham-antenna** [xproc/xvrl#10]
Indicating validity up-front is a good idea in principle (for those applications that have a binary notion of validity: https://www.w3.org/TR/xmlschema11-1/#sec-schema-validity-and-docs). However, the up-front indication requires that some part of the generating application has to buffer the error messages at least until the first error message that's recognisably for a non-valid condition.

This raises the question of whether it is possible to have 'error'-level reports that do not affect validity, but that's not my main concern.

An existing application that generates text error messages as errors occur might be easy enough to retrofit to generate XVRL messages if doing that doesn't require too many changes to the plumbing, but the up-front validity indication might be the thing that is hardest to add.

#5 points out that the number of errors and of warnings can be worked out from the document.  I don't know that you can work out validity based on whether or not there are error messages.

Maybe `validation-report`  could instead have an optional final element that indicates validity?

**Comment by gimsieke** [comment]
I agree. Maybe we can move the current `@valid` attribute (and also the other suggested attributes, such as `@errors`) to a `status` or `summary` element that may occur at any position within `validation-report`.

**Comment by gimsieke** [comment]
(or either at the beginning or at the end)

**Comment by gimsieke** [comment]
There’s now a `digest` element that may come after all `report` elements. See 400e55e and https://github.com/xproc/xvrl/issues/5#issuecomment-487599715

**Comment by tgraham-antenna** [comment]
This issue is resolved, thank you.
